sudo: true
language: python
dist: trusty
python: 3.6

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install PyQt5
  - pip install -r test-requirements.txt
  - sudo apt-get --yes install xvfb herbstluftwm

script:
  - flake8 tests webmacs setup.py
  - pytest tests
